USE SUCOS;

SELECT * FROM tbcliente; 

SELECT * FROM tbcliente WHERE IDADE = 22;

SELECT * FROM tbcliente WHERE IDADE <> 22;

SELECT * FROM tbproduto WHERE PRECO_LISTA = 16.008;

SELECT * FROM tbproduto WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;

SELECT * FROM tabela_de_vendedores WHERE PERCENTUAL_COMISSÃO > 0.10;